force-app/main/default/objects/Flow__c/Flow__c.object-meta.xml
<CustomObject>
    <label>Flow</label>
    <nameField>
        <displayFormat>F-{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Flow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listener__c/Listener__c.object-meta.xml
<CustomObject>
    <label>Listener</label>
    <nameField>
        <label>Listener Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listeners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listener__c/fields/Field_To_Track__c.field-meta.xml
<CustomField>
    <fullName>Field_To_Track__c</fullName>
    <description>A designated field within the monitored object whose alterations are tracked by Flowdometer.</description>
    <inlineHelpText>Choose Field (eg: Status or Stage) you&apos;d like to track changes on</inlineHelpText>
    <label>Field To Track</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listener__c/fields/Last_Execution_On__c.field-meta.xml
<CustomField>
    <fullName>Last_Execution_On__c</fullName>
    <label>Last Execution On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Listener__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>The Salesforce object that is monitored by the Flowdometer listener.</description>
    <inlineHelpText>Choose Object that has the field you&apos;d like Tracked</inlineHelpText>
    <label>Object To Track</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/TestDataFactory_20231014163158.cls
public class TestDataFactory {

  public static List<Opportunity> createAndUpdateOpportunities(
    Id parentId,
    String field,
    Integer numRecords
  ) {
    // Create Opportunities
    List<Opportunity> opps = new List<Opportunity>();
    for (Integer i = 0; i < numRecords; i++) {
      Opportunity opp = new Opportunity(
        Name='Test Opp ' + i,
        stageName='Prospecting',
        CloseDate=System.today(),
        AccountId=parentId,
        Type='New Business'
      );
      opps.add(opp);
    }
    insert opps;

    // Update Opportunities to generate history records
    for (Opportunity opp : opps) {
      opp.put(field, 'New Value ' + DateTime.now().getTime());  // Update the field to track
    }
    update opps;

    return opps;  // Return the list of updated Opportunities
  }
  
  public static Case createCase(String subject, String status) {
    Case newCase = new Case(
      Subject = subject,
      Status = status
    );
    insert newCase;
    return newCase;
  }

  public static Listener__c createlistenerConfig(
    String objectName,
    String fieldToTrack,
    DateTime lastExecutionOn,
    Boolean insertRecord
  ) {
    Listener__c listenerConfig = new Listener__c(
      Object_Name__c = objectName,
      Field_To_Track__c = fieldToTrack,
      Last_Execution_On__c = lastExecutionOn
    );
  
    if (insertRecord) {
      insert listenerConfig;
    }
  
    return listenerConfig;
  }

  public static Opportunity createOpportunity(String name, String stageName, Date closeDate) {
    Opportunity opp = new Opportunity(
        Name = name,
        StageName = stageName,
        CloseDate = closeDate
    );
    insert opp;
    return opp;
  }

  public static List<Opportunity> createOpportunityHistoryRecords(Integer numRecords, String stageName) {
      List<Opportunity> historyRecords = new List<Opportunity>();
      for (Integer i = 0; i < numRecords; i++) {
          historyRecords.add(
              new Opportunity(
                  Name = 'Test Opportunity ' + i,
                  stageName = stageName, // Use the provided stageName parameter
                  CloseDate = Date.today().addDays(10)
              )
          );
      }
      insert historyRecords; // Insert the Opportunity records
      return historyRecords;
  }

  public static List<Flow__c> createCustomObjects(Integer numRecords) {
      List<Flow__c> customObjects = new List<Flow__c>();
      for (Integer i = 0; i < numRecords; i++) {
          customObjects.add(new Flow__c());
      }
      insert customObjects; // Insert the Flow__c records
      return customObjects;
  }

  public static Account createAccount(String accountName) {
    Account acc = new Account(
        Name = accountName
    );
    insert acc;
    return acc;
  }

}